### ISSUE TITLE
False positives can appear

### ISSUE THREAD

**Issue by walseb** [zaidan/gjk#1]
These are two identical convex boxes a long distance from each other and yet `collision` returns `Just True`:

(It becomes easier to read with word-wrap on)
```
λ> collision 99999 ([(1874.9342045000049, (-50.0)),(1874.9342045000049, 50.0),(1974.9342045000049, 50.0),(1974.9342045000049, (-50.0))], polySupport) (([(450.0, (-50.0)),(450.0, 50.0), (550.0, 50.0), (550.0, (-50.0))]), polySupport)
Just True
```

From my testing it seems as if you have one very high precision (`double`) convex box and compare that against another one with integer precision (both are using the same datatype), false-positives can appear:
```
λ> collision 99999 ([(1874.9342045000049, (-50.0)),(1874.9342045000049, 50.0),(1974.9342045000049, 50.0),(1974.9342045000049, (-50.0))], polySupport) (([(450.0, (-50.0)),(450.0, 50.0),(550.0, 50.0),(550.0, (-50.0))]), polySupport)
Just True
λ> collision 99999 ([(1874.9342045000049, (-50.0)),(1874.9342045000049, 50.0),(1974.9342045000049, 50.0),(1974.9342045000049, (-50.0))], polySupport) (([(450.0000000000001, (-50.0000000000001)),(450.0000000000001, 50.0000000000001),(550.0000000000001, 50.0000000000001),(550.0000000000001, (-50.0000000000001))]), polySupport)
Just False
λ> collision 99999 ([(1874.9342045000049, (-50.0)),(1874.9342045000049, 50.0),(1974.9342045000049, 50.0),(1974.9342045000049, (-50.0))], polySupport) (([(450.0000000000000, (-50.0000000000000)),(450.0000000000000, 50.0000000000000),(550.0000000000000, 50.0000000000000),(550.0000000000000, (-50.0000000000000))]), polySupport)
Just True
λ> collision 99999 ([(1874.9342045000049, (-50.0)),(1874.9342045000049, 50.0),(1974.9342045000049, 50.0),(1974.9342045000049, (-50.0))], polySupport) (([(449.9999999999999, (-49.9999999999999)),(449.9999999999999, 49.9999999999999),(549.9999999999999, 49.9999999999999),(549.9999999999999, (-49.9999999999999))]), polySupport)
Just False
λ> collision 99999 ([(1874, (-50.0)),(1874, 50.0),(1974, 50.0),(1974, (-50.0))], polySupport) (([(450, (-50)),(450, 50),(550, 50),(550, (-50))]), polySupport)
Just False
```
As you can see, simply adding zeroes to the second box won't fix it, but adding something trivial like `0000000000001` seems to. Also if you look at the last prompt, removing the decimals from the first cube makes it work properly again, so it has something to do with the precision

Maybe this is just a inherent problem of the algorithm? I haven't looked into it or tried this with other GJK packages.

**Comment by zaidan** [comment]
@walseb thx, for finding this bug. The bug was caused by using y = `0.0` for `d1` - see: https://github.com/zaidan/gjk/pull/3/commits/9c71e25c05a60b24828418ba4844fa355230b617#diff-4f64b18c58764991e6cf79d74e3a8e33R33

**Comment by walseb** [comment]
Wow thanks for fixing this so quickly!
